apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: dind-no-resources
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: image-url
      description: the url of the image to build
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: clone-repository
      taskRef:
        name: clone-repo-task
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
      workspaces:
        - name: workspace
          workspace: pipeline-ws
    - name: build-and-push-docker
      runAfter: [clone-repository]
      taskRef:
        name: execute-in-dind-task
      params:
        - name: image-url
          value: $(params.image-url)
      workspaces:
        - name: workspace
          workspace: pipeline-ws
    - name: va-scan-task
      runAfter: [build-and-push-docker]
      taskRef:
        name: vulnerability-advisor-task
      params:
        - name: scan-report-file
          value: 'app-image-va-report.json'
        # - name: max-iteration
        #   value: '5'
        # - name: sleep-time
        #   value: '3'
        # - name: fail-on-scanned-issues
        #   value: 'false'
        - name: image-url
          value: $(params.image-url)
      workspaces:
        - name: workspace
          workspace: pipeline-ws
