apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-simple-clone
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
  resourcetemplates:
    # CD secret to provide API_KEY to access toolchain information
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-simple-clone
        params:
          - name: pipeline-pvc
            value: pipelinerun-$(uid)-pvc
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-simple-clone
spec:
  params:
    - name: branch
      value: "master"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-simple-clone
spec:
  triggers:
    - binding:
        name: trigger-binding-simple-clone
      template:
        name: trigger-template-simple-clone
