apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-pr-processing
spec:
  params:
    - name: gitAccessToken
      description: the token to access the git repository for the clone operations
    - name: apikey
      description: the ibmcloud api key
      default: ' '
    - name: repository
      description: The git repo
      default: ' '
    - name: branch
      description: the branch for the git repo
    - name: revision
      default: ' '
    - name: pr_repository
      default: ' '
    - name: pr_branch
      default: ' '
    - name: pr_revision
      default: ' '
    - name: triggerName
      default: 'git-pr-process'
  resourcetemplates:
    # CD secret to provide API_KEY to access toolchain information
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: $(params.triggerName)-$(uid)
      spec:
        pipelineRef:
          name: pipeline-git-event-processing
        params:
          - name: pipeline-pvc
            value: $(params.triggerName)-$(uid)-pvc
          - name: gitAccessToken
            value: $(params.gitAccessToken)
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: pr_repository
            value: $(params.pr_repository)
          - name: pr_branch
            value: $(params.pr_branch)
          - name: pr_revision
            value: $(params.pr_revision)
    - apiVersion: tekton.dev/v1alpha1
      kind: Task
      metadata:
        name: inspect-content-task
      spec:
        inputs:
          params:
            - name: task-pvc
              description: the output pvc - this is where the cloned repository will be stored
            - name: repository
              description: the git repo url
            - name: directoryName
              default: '.'
        steps:
          - name: inspect-git-content
            image: alpine/git
            env:
              - name: REPOSITORY
                value: $(inputs.params.repository)
              - name: DIRECTORY_NAME
                value: $(inputs.params.directoryName)
            command: ["/bin/sh", "-c"]
            args:
              - |
                # cd in the directory of the previous git operations
                cd /artifacts
                if [ -z "$DIRECTORY_NAME" ]; then
                  # Find the "humanish" part of the git source repository that corresponds to the clone directory
                  # GIT_REPOSITORY contains the repository url with .git suffix
                  DIRECTORY_NAME=$(basename "${GIT_REPOSITORY##*/}" .git)
                fi
                # show the git content
                git show-branch --all
                echo "##############"
                # show the directory content as a tree
                apk update && apk add tree
                echo "##############"
                tree
                # show the README.md content
                echo "##############"
                cat README.md
                echo ""
            volumeMounts:
              - mountPath: /artifacts
                name: task-volume      
        volumes:
          - name: task-volume
            persistentVolumeClaim:
              claimName: $(inputs.params.task-pvc)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-pr-processing-manual
spec:
  params:
    - name: branch
      value: "master"
    - name: triggerName
      value: manual-trigger
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-pr-processing-manual
spec:
  triggers:
    - binding:
        name: trigger-binding-pr-processing-manual
      template:
        name: trigger-template-pr-processing
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-pr-processing-github-pr-event
spec:
  params:
    # For PR, the repo to clone first is the base repo (target of the PR)
    - name: repository
      value: "$(event.pull_request.base.repo.clone_url)"
    - name: branch
      value: "$(event.pull_request.base.ref)"
    # Do we want to really use the revision when the PR was made ?
    # if yes, it may miss update in the initial branch but just uncomment the line
    # - name: revision
    #   value: $(event.pull_request.base.sha)
    # Then the origin of the update to incorporate is from the PR head
    - name: pr_repository
      value: "$(event.pull_request.head.repo.clone_url)"
    - name: pr_branch
      value: "$(event.pull_request.head.ref)"
    - name: pr_revision
      value: "$(event.pull_request.head.sha)"
    - name: triggerName
      value: "github-pr-trigger"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-pr-processing-github-commit-event
spec:
  params:
    - name: repository
      value: "$(event.repository.url)"
    - name: revision
      value: "$(event.head_commit.id)"
    - name: branch
      value: "master"
    - name: triggerName
      value: "github-commit-trigger"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-pr-processing-github-pr-event
spec:
  triggers:
    - binding:
        name: trigger-binding-pr-processing-github-pr-event
      template:
        name: trigger-template-pr-processing
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-pr-processing-github-commit-event
spec:
  triggers:
    - binding:
        name: trigger-binding-pr-processing-github-commit-event
      template:
        name: trigger-template-pr-processing
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-pr-processing-grit-pr-event
spec:
  params:
    - name: repository
      value: "$(event.object_attributes.target.git_http_url)"
    - name: branch
      value: "$(event.object_attributes.target_branch)"
    # - name: revision
    #   value: $(event.pull_request.head.sha)
    - name: pr_repository
      value: "$(event.object_attributes.source.git_http_url)"
    - name: pr_branch
      value: "$(event.object_attributes.source_branch)"
    - name: pr_revision
      value: "$(event.object_attributes.last_commit.id)"
    - name: triggerName
      value: "grit-merge-request-trigger"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-pr-processing-grit-commit-event
spec:
  params:
    - name: repository
      value: "$(event.repository.git_http_url)"
    - name: revision
      value: "$(event.checkout_sha)"
    - name: branch
      value: "master"
      # value: "$(event.ref)"
    - name: triggerName
      value: "grit-commit-trigger"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-pr-processing-grit-pr-event
spec:
  triggers:
    - binding:
        name: trigger-binding-pr-processing-grit-pr-event
      template:
        name: trigger-template-pr-processing
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-pr-processing-grit-commit-event
spec:
  triggers:
    - binding:
        name: trigger-binding-pr-processing-grit-commit-event
      template:
        name: trigger-template-pr-processing
