apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-simple-clone
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: pipeline-simple-clone-task
      taskRef:
        name: clone-repo-task
      workspaces:
        - name: workspace
          workspace: pipeline-ws
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
