---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: dind-cluster-no-resources
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
    - name: image-url
      description: The image url in your container registry
    - name: build-cluster
      description: name of the cluster that will host the docker dind to build docker images
    - name: pipeline-debug
      default: "0"
    - name: properties-file
      default: ""
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: dind-cluster-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: dind-cluster-$(uid)
      spec:
        pipelineRef:
          name: dind-cluster-no-resources
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: image-url
            value: $(params.image-url)
          - name: cluster-name
            value: $(params.build-cluster)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: properties-file
            value: $(params.properties-file)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: dind-cluster-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: dind-cluster-no-resources
spec:
  params:
    - name: branch
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: dind-cluster-no-resources
spec:
  triggers:
    - binding:
        name: dind-cluster-no-resources
      template:
        name: dind-cluster-no-resources
