apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-dind-cluster
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
    - name: apikey
      description: the ibmcloud api key
    - name: imageUrl
      description: The image url in your container registry
    - name: buildCluster
      description: name of the cluster that will host the docker dind to build docker images
  resourcetemplates:
    # CD secret to provide API_KEY to access toolchain information
    - apiVersion: v1
      kind: Secret
      metadata:
        name: secure-properties
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: image-to-build
      spec:
        type: image
        params:
          - name: url
            value: $(params.imageUrl)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: $(params.buildCluster)
      spec:
        type: cluster
        params:
          # name is required in tekton v0.7 but not in v0.10.1
          - name: name
            value: $(params.buildCluster)
          #
          - name: username
            value: username
          - name: url
            value: https://to.be.updated
          - name: token
            value: token
          - name: cadata
            value: cadata
    # PVC definition like pre-tekton-0.10.1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: dind-cluster-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: dind-cluster-$(uid)
      spec:
        pipelineRef:
          name: pipeline-dind-cluster
        resources:
          - name: app-image
            resourceRef:
              name: image-to-build
          - name: build-cluster
            resourceRef:
              name: $(params.buildCluster)
        params:
          - name: pipeline-pvc
            value: dind-cluster-$(uid)-pvc
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-dind-cluster
spec:
  params:
    - name: branch
      value: "master"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-dind-cluster
spec:
  triggers:
    - binding:
        name: trigger-binding-dind-cluster
      template:
        name: trigger-template-dind-cluster
