apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-dind-cluster
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
  resources:
  - name: app-image
    type: image
  - name: build-cluster
    type: cluster
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: clone-repository
      taskRef:
        name: clone-repo-task
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
      workspaces:
        - name: workspace
          workspace: pipeline-ws
    - name: build-and-push-docker
      runAfter: [clone-repository]
      taskRef:
        name: execute-in-dind-cluster-task
      params:
      workspaces:
        - name: workspace
          workspace: pipeline-ws
      resources:
        inputs:
          - name: cluster
            resource: build-cluster
        outputs:
          - name: builtImage
            resource: app-image
    - name: va-scan-task
      taskRef:
        name: vulnerability-advisor-task
      params:
        - name: scan-report-file
          value: 'app-image-va-report.json'
        # - name: max-iteration
        #   value: '5'
        # - name: sleep-time
        #   value: '3'
        # - name: fail-on-scanned-issues
        #   value: 'false'
      workspaces:
        - name: workspace
          workspace: pipeline-ws
      resources:
        inputs:
          - name: image
            resource: app-image
            from:
              - build-and-push-docker
