---
apiVersion: tekton.dev/v1
kind: TriggerTemplate
metadata:
  name: triggertemplate-sample-environment
spec:
  params:
    - name: pipeline-debug
      description: Pipeline debug mode. Value can be 0 or 1.
      default: "0"
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        name: inspect-environment-$(uid)
      spec:
        pipelineRef:
          name: pipeline-sample-environment
        params:
          - name: pipeline-debug
            value: $(params.pipeline-debug)
---
apiVersion: tekton.dev/v1
kind: TriggerBinding
metadata:
  name: triggerbinding-sample-environment
spec:
  params:
---
apiVersion: tekton.dev/v1
kind: EventListener
metadata:
  name: eventlistener-sample-environment
  annotations:
    tekton.dev/displayName: "trigger for sample environment"
spec:
  triggers:
    - binding:
        name: triggerbinding-sample-environment
      template:
        name: triggertemplate-sample-environment
