apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-post-slack
spec:
  params:
  resourcetemplates:
    # PVC definition like pre-tekton-0.10.1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: post-a-message-to-slack-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: post-a-message-to-slack-$(uid)
      spec:
        pipelineRef:
          name: pipeline-slack
        params:
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: post-a-message-to-slack-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-post-slack
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-post-slack
spec:
  triggers:
    - binding:
        name: trigger-binding-post-slack
      template:
        name: trigger-template-post-slack
