apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-slack
spec:
  params:
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: post-to-slack
      taskRef:
        name: slack-post-message
      params:
      workspaces:
        - name: workspace
          workspace: pipeline-ws
