apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cr-build
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
    - name: pathToDockerfile
      default: '.'
  resources:
  - name: app-image
    type: image
  tasks:
    - name: pipeline-1-clone-task
      taskRef:
        name: clone-repo-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
    - name: pipeline-2-cr-build-task
      runAfter: [pipeline-1-clone-task]
      taskRef:
        name: cr-build-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: pathToContext
          value: $(params.pathToDockerfile)
        - name: pathToDockerfile
          value: $(params.pathToDockerfile)
        - name: additionalTags
          value: 'latest'
        - name: additionalTagsScript
          value: |
            # Include the clone task output variables in the environment
            source /artifacts/build.properties
            # The script is providing tag(s) as output
            # But logs can be written as error stderr
            echo "Providing an image tag including git branch and commit" >&2
            # Add a specific tag with branch and commit
            echo "1.0.0-${GIT_BRANCH}-${GIT_COMMIT}"
            # Add a specific tag with cd build number
            echo "1.0.0-${BUILD_NUMBER}"            
      resources:
        outputs:
          - name: builtImage
            resource: app-image
    - name: pipeline-3-va-task
      taskRef:
        name: vulnerability-advisor-task
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: scanReportFile
          value: 'app-image-va-report.json'
        # - name: maxIteration
        #   value: '5'
        # - name: sleepTime
        #   value: '3'
        # - name: failOnScannedIssues
        #   value: 'false'
      resources:
        inputs:
          - name: image
            resource: app-image
            from:
              - pipeline-2-cr-build-task
