apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kubernetes-contextual-execution
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc - this is the volume valid for the lifetime of the pipelinerun
      - name: task-pvc-mountpath
        default: /artifacts
      # As Cluster Pipeline Resources are not properly updated after kubernetes cluster setup
      # Allow user to specifiy kubeconfig copy fallback directory provided by fetch-iks-cluster-context task
      - name: clusterPipelineResourcesDirectory
        description: directory in which the kubeconfig file(s) for clusterPipelineResources are available
        default: /workspace
      - name: script
        description: the bash snippet to execute within the context of the kubernetes configuration
        default: 'kubectl version'
    resources:
      - name: cluster
        type: cluster
  stepTemplate:
    env:
      - name: KUBECONFIG
        value: $(inputs.params.clusterPipelineResourcesDirectory)/$(inputs.resources.cluster.name)/kubeconfig
  steps:
    - name: execute
      image: ibmcom/pipeline-base-image
      workingDir: $(inputs.params.task-pvc-mountpath)
      command: ["/bin/bash", "-c"]
      args: 
        - |
          # Validate KUBECONFIG 
          if test -f "$KUBECONFIG"; then
            echo "KUBECONFIG=$KUBECONFIG"
          else
            echo "$KUBECONFIG file is not existing. exiting now..."
            exit 1
          fi
          # User-defined snippet/script
          $(inputs.params.script)
      volumeMounts:
        - mountPath: $(inputs.params.task-pvc-mountpath)
          name: task-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
