---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: signing-dct-sign
spec:
  params:
    - name: image-repository
      description: the repository of the image to sign
    - name: image-digest
      description: the image digest (sha-256 hash) for the image to sign
    - name: image-tags
      description: the tags for the image to sign
    - name: signer
      description: current signer
    - name: registry-region
      description: the registry region
    - name: vault-region
      description: the region of the keyprotect instance
    - name: vault-resource-group
      description: the resource group of the keyprotect instance
    - name: vault-name
      description: the key protect instance name
    - name: ibmcloud-api
      description: the ibmcloud api
      default: https://cloud.ibm.com
    - name: continuous-delivery-context-secret
      description: name of the secret containing the continuous delivery pipeline context secrets
      default: secure-properties
    - name: apikey-secret-key
      description: field in the secret that contains the api key used to login to ibmcloud service
      default: apikey
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
  workspaces:
    - name: artifacts
      description: A workspace backing by a volume
      mountPath: /artifacts
  steps:
    - name: sign-image
      image: ibmcom/pipeline-base-image:2.6
      env:
        - name: IBM_CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.continuous-delivery-context-secret)
              key: $(params.apikey-secret-key)
        - name: REGISTRY_REGION
          value: $(params.registry-region)
        - name: IMAGE_REPOSITORY
          value: $(params.image-repository)
        - name: IMAGE_DIGEST
          value: $(params.image-digest)
        - name: IMAGE_TAGS
          value: $(params.image-tags)
        - name: DEVOPS_SIGNER
          value: $(params.signer)
        - name: VAULT_REGION
          value: $(params.vault-region)
        - name: VAULT_RESOURCE_GROUP
          value: $(params.vault-resource-group)
        - name: VAULT_INSTANCE
          value: $(params.vault-name)
        - name: ARCHIVE_DIR
          value: /artifacts
        - name: HOME
          value: /root
        # Docker client configuration
        # Connect to the sidecar over TCP, with TLS.
        - name: DOCKER_HOST
          value: "tcp://localhost:2376"
        # Verify TLS.
        - name: DOCKER_TLS_VERIFY
          value: "1"
        # Use the certs generated by the sidecar daemon.
        - name: DOCKER_CERT_PATH
          value: /certs/client
        - name: PIPELINE_DEBUG
          value: $(params.pipeline-debug)
      workingDir: /artifacts
      script: |
          #!/bin/bash

          if [ $PIPELINE_DEBUG == 1 ]; then
           pwd
           env
           trap env EXIT
           set -x
          fi

          echo "ADD DOCKER"
          source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/\
          scripts/image_signing/add_docker.sh")

          # if vault region is in the 'ibm:yp:<region>' just keep the region part
          export VAULT_REGION=$(echo "$VAULT_REGION" | awk -F ':' '{print $NF;}')

          ibmcloud config --check-version false
          ibmcloud login --apikey "$IBM_CLOUD_API_KEY" -r "$VAULT_REGION"

          if [ -z "$VAULT_RESOURCE_GROUP" ]; then
            echo "Using default resource group" 
          else
            ibmcloud target -g "$VAULT_RESOURCE_GROUP"
          fi

          # configure the container registry
          REGISTRY_REGION=$(echo "$REGISTRY_REGION" | awk -F ':' '{print $NF;}')
          ibmcloud cr region-set $REGISTRY_REGION
          ibmcloud cr login
          export REGISTRY_URL=$(ibmcloud cr info | grep -m1 -i '^Container Registry' | awk '{print $3;}')
          export DOCKER_CONTENT_TRUST_SERVER="https://$REGISTRY_URL:4443"

          #TODO support multiple signatures. This requires knowing if there is already a signature present.
          #Need to set DOCKER_CONTENT_TRUST=1 before the image pull if singture present
          IMAGE_TAG=$IMAGE_TAGS

          echo "CHECKING $IMAGE_REPOSITORY:$IMAGE_TAG"
          docker trust inspect "$IMAGE_REPOSITORY:$IMAGE_TAG"

          # Split image information in expected environment variables
          REGISTRY_URL=$(echo $IMAGE_REPOSITORY |  awk -F/ '{print $1}')
          REGISTRY_NAMESPACE=$(echo $IMAGE_REPOSITORY |  awk -F/ '{print $2}')
          # Image name is remaining part after the repository and namespace and can contains /
          IMAGE_NAME=$(echo $IMAGE_REPOSITORY |  awk -F/ '{a=match($0, $3); print substr($0,a)}')

          # Requires
          # $VAULT_INSTANCE -name of vault
          # $VAULT_REGION or default to $IBMCLOUD_TARGET_REGION -region hosting Key Protect Vault instance
          # $VAULT_RESOURCE_GROUP or default to $IBMCLOUD_TARGET_RESOURCE_GROUP - resourcegroup of the Key Protect Vault Instance
          # $REGISTRY_URL - url/domain of the registry
          # $REGISTRY_NAMESPACE -namespace of registry
          # $IMAGE_NAME
          # $IMAGE_TAG
          # $DEVOPS_SIGNER
          export DOCKER_CONTENT_TRUST=1
          echo "Vault instance $VAULT_INSTANCE used to retrieve signing keys"
          source <(curl -sSL "https://raw.githubusercontent.com/open-toolchain/commons/master/scripts/image_signing/signing_utils.sh")
          # Restore signer pem key
          VAULT_DATA=$(buildVaultAccessDetailsJSON "$VAULT_INSTANCE" "${VAULT_REGION:-$IBMCLOUD_TARGET_REGION}" "${VAULT_RESOURCE_GROUP:-$IBMCLOUD_TARGET_RESOURCE_GROUP}")
          JSON_DATA="$(readData "$REGISTRY_NAMESPACE.keys" "$VAULT_DATA")"
          signerkey=$(getJSONValue "$DEVOPS_SIGNER" "$JSON_DATA")
          writeFile "$signerkey"
          # Retrieve the signer passphrase
          export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=$(getJSONValue "passphrase" "$signerkey")

          export DCT_DISABLED=false
          # Pull the image
          docker pull "$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG"
          # Sign the image
          docker trust sign "$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:$IMAGE_TAG"
          docker trust inspect --pretty "$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME"
    # yamllint enable rule:line-length
      volumeMounts:
        - mountPath: /certs/client
          name: dind-certs
  sidecars:
    - image: docker:dind
      name: server
      securityContext:
        privileged: true
      env:
        # Write generated certs to the path shared with the client.
        - name: DOCKER_TLS_CERTDIR
          value: /certs
      volumeMounts:
        - mountPath: /certs/client
          name: dind-certs
      # Wait for the dind daemon to generate the certs it will share with the client.
      readinessProbe:
        periodSeconds: 1
        exec:
          command: ["ls", "/certs/client/ca.pem"]
  volumes:
    - name: dind-certs
      emptyDir: {}
