apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: slack-post-message
spec:
  params:
    - name: domain
      description: the Slack domain to send the message to. If not set, the message will be posted to the Slack integration(s) as defined in the Toolchain.
      default: ""
    - name: channel
      description: the Slack channel to send the message to. When set, overrides the default channel as set in the Slack Webhook URL.
      default: ""
    - name: message-format
      description: the format of the message. text(default) or JSON payload.
      default: text
    - name: message-script
      description: Shell script that provides messsage content.
      default: ""
    - name: message
      description: the message to send to Slack
      default: 'Tekton Pipeline completed successfully. :heavy_check_mark:\nVisit *<https://api.slack.com/reference/surfaces/formatting|More on Slack message formatting.>*'
    - name: exit-on-error
      description: flag (`true` | `false`) to indicate if the task should fail or continue if unable to process the message or post to Slack.
      default: "false"
  workspaces:
    - name: workspace
      description: A workspace that contain data useful for the script/slack message resolution. Should be marked as optional when Tekton will permit it
      mountPath: /artifacts
  steps:
    - name: post-to-slack
      # tbd: use an image with curl and jq?
      image: ibmcom/pipeline-base-image:2.6
      env:
        # keep slack message injected in an env var to let YAML manage the quote for us
        - name: SLACK_MESSAGE
          value: $(params.message)
        - name: PIPELINE_RUN_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tekton.dev/pipelineRun']
        - name: PIPELINE_RUN_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']
        - name: BUILD_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']
        - name: PIPELINE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-id']
        - name: TRIGGER_TYPE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/trigger-type']
        - name: TRIGGER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/trigger-name']
        - name: TRIGGERED_BY
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/triggered-by']
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail

          export TOOLCHAIN_ID=$(jq -r '.toolchain_guid' /cd-config/toolchain.json)
          export TOOLCHAIN_REGION=$(jq -r '.region_id' /cd-config/toolchain.json | awk -F: '{print $3}')

          # Dynamically set message if message-script param is set
          printf "#!/bin/sh\n" > /steps/message-script.sh
          printf "%s " '$(params.message-script)' >> /steps/message-script.sh
          chmod +x /steps/message-script.sh
          /steps/message-script.sh 2 >& 1 > /steps/message.content
          if [ -s /steps/message.content ]; then
            echo "************************************"
            echo "Snippet for dynamic message content:"
            cat /steps/message-script.sh
            echo ""
            echo "************************************"
          else
             echo "${SLACK_MESSAGE}" > /steps/message.content
          fi

          # message.content was passed as a slack json payload: keep it as-is
          if [[ "$(params.message-format)" != "text" ]]; then
            mv /steps/message.content /steps/payload.json
          fi

          # Handle domain
          SLACK_DOMAIN=$(echo $(params.domain))
          if [ -z "$SLACK_DOMAIN" ]; then
            echo "No Slack domain passed as parameter. Sending to the Slack integration(s) as defined in the Toolchain."
          else
            echo "Retrieving Slack webhook(s) for $SLACK_DOMAIN domain."
            # to be added to jq query
            SELECT_DOMAIN='| select (.parameters.team_url=="'"${SLACK_DOMAIN}"'")'
          fi

          # Handle channel
          SLACK_CHANNEL=$(echo $(params.channel))

          # Post message
          msgSent=0
          msgFail=0
          for SLACK_INTEGRATION in $(cat /cd-config/toolchain.json | jq -c -r '.services[] | select (.service_id=="slack") '"${SELECT_DOMAIN}"' | (.parameters) | ({"webhook":.api_token, "channel":.channel_name})')
          do
            WEBHOOK=$(echo ${SLACK_INTEGRATION} | jq -r ' .webhook')
            if [[ "$(params.message-format)" == "text" ]]; then
              if [ "$SLACK_CHANNEL" ]; then
                CHANNEL=$SLACK_CHANNEL
                echo "Posting to channel $CHANNEL as passed as parameter."
              else
                CHANNEL=$(echo ${SLACK_INTEGRATION} | jq -r ' .channel')
                echo "Posting to channel $CHANNEL as defined in Slack integration."
              fi
              # format message to a Slack JSON payload
              echo "Formatting text message to JSON."
              echo '{"channel": "'"${CHANNEL}"'", "type": "text"}' | jq --rawfile text /steps/message.content '.text=$text' > /steps/payload.json
            fi
            echo "Slack Message payload:"
            cat /steps/payload.json
            echo ""
            echo "Posting Slack Message..."
            status_code=$(curl -s -X POST -H 'Content-type: application/json' -d @/steps/payload.json -o /dev/null -w "%{http_code}" "$WEBHOOK")
            if [[ $status_code -eq 200 ]]; then
              echo ""
              echo "Message successfully posted to Slack."
              echo ""
              msgSent=$((msgSent+1))
            else
              echo ""
              echo "Failed to post the message to Slack with status code: $status_code."
              echo "More details about $status_code error: https://api.slack.com/changelog/2016-05-17-changes-to-errors-for-incoming-webhooks."
              echo ""
              # keep track of failures
              msgFail=$((msgFail+1))
            fi
            if [ "$SLACK_CHANNEL" ]; then
              # don't send the same message more than once if channel was specified
              break
            fi
          done
          echo "Done: ${msgSent} message(s) posted to Slack (${msgFail} failure(s))."

          # Handle exit based on error if any
          if [[ $msgFail -ne 0 ]] && [[ "$(params.exit-on-error)" == "true" ]]; then
            exit 1
          fi
      volumeMounts:
        - mountPath: /steps
          name: steps-volume
        - mountPath: /cd-config
          name: cd-config-volume
  volumes:
    - name: steps-volume
      emptyDir: {}
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
          - key: toolchain.json
            path: toolchain.json
