apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-post-slack
spec:
  params:
    # TriggerTemplate default param values are not taken into account if empty string
    # hence put a single space string value as workaround
    # https://github.ibm.com/org-ids/roadmap/issues/11640
    - name: domain
      description: the Slack domain to send the message to. If not set, the message will be posted to the Slack integration(s) as defined in the Toolchain.
      default: ' '
    - name: channel
      description: the Slack channel to send the message to. When set, overrides the default channel as set in the Slack Webhook URL.
      default: ' '
    - name: message-format
      description: the format of the message. text(default) or JSON.
      default: text
    - name: message
      description: the message to send to Slack
      default: 'Tekton Pipeline completed successfully. :heavy_check_mark:\nVisit *<https://api.slack.com/reference/surfaces/formatting|More on Slack message formatting.>*'
    - name: message-script
      description: |
          any custom script that will be executed by the task to provide a message.
          Reference: https://api.slack.com/reference/surfaces/formatting
          For instance: echo "Message injected by message-script. :heavy_check_mark:\nVisit *<https://api.slack.com/reference/surfaces/formatting|More on Slack message formatting.>*"
      default: ' '
    - name: exit-on-error
      description: flag (`true` | `false`) to indicate if the task should fail or continue if unable to process the message or post to Slack.
      default: 'false'
  resourcetemplates:
    # PVC definition like pre-tekton-0.10.1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: post-a-message-to-slack-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: post-a-message-to-slack-$(uid)
      spec:
        pipelineRef:
          name: pipeline-slack
        params:
          - name: domain
            value: $(params.domain)
          - name: channel
            value: $(params.channel)
          - name: message
            value: $(params.message)
          - name: message-format
            value: $(params.message-format)
          - name: message-script
            value: $(params.message-script)
          - name: exit-on-error
            value: $(params.exit-on-error)
        workspaces:
        - name: pipeline-ws
          persistentVolumeClaim:
            claimName: post-a-message-to-slack-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-post-slack
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-post-slack
spec:
  triggers:
    - binding:
        name: trigger-binding-post-slack
      template:
        name: trigger-template-post-slack
