apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-post-slack
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    # TriggerTemplate default param values are not taken into account
    # https://github.ibm.com/org-ids/roadmap/issues/11640
    - name: domain
      description: the Slack domain to send the message to. If not set, the message will be posted to the Slack integration(s) as defined in the Toolchain.
      default: ' '
    - name: channel
      description: the Slack channel to send the message to. When set, overrides the default channel as set in the Slack Webhook URL.
      default: ' '
    - name: messageFormat
      description: the format of the message. text(default) or JSON.
      default: text 
    - name: message
      description: the message to send to Slack
      default: 'Tekton Pipeline completed successfully. :heavy_check_mark:\nVisit *<https://api.slack.com/reference/surfaces/formatting|More on Slack message formatting.>*'
    - name: messageScript
      description: | 
          any custom script that will be executed by the task to provide a message.
          Reference: https://api.slack.com/reference/surfaces/formatting
          For instance: echo "Message injected by messageScript. :heavy_check_mark:\nVisit *<https://api.slack.com/reference/surfaces/formatting|More on Slack message formatting.>*"
      default: ' '
    - name: exitOnError
      description: flag (`true` | `false`) to indicate if the task should fail or continue if unable to process the message or post to Slack.
      default: 'false'
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-slack
        params:
          - name: pipeline-pvc
            value: pipelinerun-$(uid)-pvc
          - name: domain
            value: $(params.domain)
          - name: channel
            value: $(params.channel)
          - name: message
            value: $(params.message)
          - name: messageFormat
            value: $(params.messageFormat)
          - name: messageScript
            value: $(params.messageScript)
          - name: exitOnError
            value: $(params.exitOnError)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-post-slack
spec:
  params:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-post-slack
spec:
  triggers:
    - binding:
        name: trigger-binding-post-slack
      template:
        name: trigger-template-post-slack
