apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-slack
spec:
  params:
    - name: pipeline-pvc
      description: the pipeline pvc name
    - name: domain
      description: the Slack domain to send the message to. If not set, the message will be posted to the Slack integration(s) as defined in the Toolchain.
    - name: channel
      description: the Slack channel to send the message to. When set, overrides the default channel as set in the Slack Webhook URL.
    - name: messageFormat
      description: the format of the message. text(default) or JSON.
    - name: messageScript
      description: Shell script that provides messsage content.
    - name: message
      description: the message to send to Slack
    - name: exitOnError
      description: flag (`true` | `false`) to indicate if the task should fail or continue if unable to process the message or post to Slack.
  tasks:
    - name: post-to-slack
      taskRef:
        name: post-slack
      params:
        - name: task-pvc
          value: $(params.pipeline-pvc)
        - name: domain
          value: $(params.domain)
        - name: channel
          value: $(params.channel)
        - name: messageFormat
          value: $(params.messageFormat)
        - name: message
          value: $(params.message)
        - name: messageScript
          value: $(params.messageScript)
        - name: exitOnError
          value: $(params.exitOnError)
