---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: buildkit-no-resources
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
    - name: image-url
      description: The image url in your container registry
    - name: path-to-dockerfile
      default: "."
    - name: pipeline-debug
      default: "0"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: buildkit-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: buildkit-nr-$(uid)
      spec:
        pipelineRef:
          name: buildkit-no-resources
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: image-url
            value: $(params.image-url)
          - name: path-to-dockerfile
            value: $(params.path-to-dockerfile)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: buildkit-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: buildkit-no-resources
spec:
  params:
    - name: branch
      value: "master"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: buildkit-no-resources
spec:
  triggers:
    - binding:
        name: buildkit-no-resources
      template:
        name: buildkit-no-resources
