apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: pipeline-container-registry
spec:
  params:
    - name: repository
      description: the git repo
    - name: branch
      description: the branch for the git repo
  resources:
  - name: app-image
    type: image
  workspaces:
    - name: pipeline-ws
  tasks:
    - name: pipeline-1-clone-task
      taskRef:
        name: clone-repo-task
      params:
        - name: repository
          value: $(params.repository)
        - name: branch
          value: $(params.branch)
      workspaces:
        - name: artifacts
          workspace: pipeline-ws
    - name: pipeline-2-containerize-task
      runAfter: [pipeline-1-clone-task]
      taskRef:
        name: containerize-task
      params:
        - name: additionalTags
          value: '1.0.0-dev'
        - name: additionalTagsScript
          value: |
            # Include the clone task output variables in the environment
            source /artifacts/build.properties
            # The script is providing tag(s) as output
            # But logs can be written as error stderr
            echo "Providing an image tag including git branch and commit" >&2
            # Add a specific tag with branch and commit
            echo "1.0.0-${GIT_BRANCH}-${GIT_COMMIT}"
      workspaces:
        - name: workspace
          workspace: pipeline-ws
      resources:
        outputs:
          - name: builtImage
            resource: app-image
    - name: pipeline-3-va-task
      taskRef:
        name: vulnerability-advisor-task
      params:
        - name: scanReportFile
          value: 'app-image-va-report.json'
        # - name: maxIteration
        #   value: '5'
        # - name: sleepTime
        #   value: '3'
        # - name: failOnScannedIssues
        #   value: 'false'
      workspaces:
        - name: workspace
          workspace: pipeline-ws
      resources:
        inputs:
          - name: image
            resource: app-image
            from:
              - pipeline-2-containerize-task
