---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: utils-evaluate
  labels:
    tekton.dev/deprecated: "true"
spec:
  params:
    - name: value
    - name: condition
      default: '='
    - name: expected
      default: 'true'
  check:
    image: alpine
    command: ["/bin/sh", "-c"]
    args:
      - |
        if [ "$(params.value)" $(params.condition) "$(params.expected)" ]; then
          exit 0
        else
          exit 1
        fi
