apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: skip-ci
spec:
  workspaces:
    - name: workspace
      description: The workspace containing the cloned repo
      mountPath: /artifacts
  inputs:
    params:
      - name: repository-dir
        description: The directory the repository was cloned into, relative to workspace path.
      - name: build-properties
        description: |
          (optional) If this file is provided, build does not fail.
          Instead, skip_ci=true gets wrtten in the file.
        default: ''
  steps:
    - name: check-commit-message
      image: ibmcom/pipeline-base-image
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e
          cd $(workspaces.workspace.path)/$(inputs.params.repository-dir)

          commit_message=$(git show -s --format=%s)
          echo $commit_message

          if [[ "${commit_message}" = "[skip ci]"* ]]; then
            if [[ "" = "$(inputs.params.build-properties)" ]]; then
              exit 1
            else
              echo skip_ci=true >> $(workspaces.workspace.path)/$(inputs.params.build-properties)
            fi
          fi
