---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: gitlab-pr-binding
spec:
  params:
    - name: branch
      value: $(event.object_attributes.source_branch)
    - name: target-branch
      value: $(event.object_attributes.target_branch)
    - name: commit-id
      value: $(event.object_attributes.last_commit.id)
    - name: commit-timestamp
      value: $(event.object_attributes.last_commit.timestamp)
    - name: target-commit-id
      value: $(event.merge_request.base.sha)
    - name: pr-url
      value: $(event.object_attributes.url)
    - name: pr-number
      value: $(event.object_attributes.iid)
    - name: pr-name
      value: $(event.user.username)
    - name: project-id
      value: $(event.project.id)
    - name: scm-type
      value: "gitlab"
    - name: repository
      value: $(event.project.http_url)
