---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pr-template
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: branch
    - name: target-branch
      description: target branch
    - name: target-commit-id
      description: target commit id
    - name: apikey
      description: the ibmcloud api key
    - name: commit-id
      description: commit id
    - name: commit-timestamp
      description: commit timestamp
    - name: pipeline-debug
      description: toggles debug mode for the pipeline
      default: "0"
    - name: pr-url
      description: PR url
    - name: pr-number
      description: PR number
    - name: pr-name
      description: PR name
    - name: scm-type
      description: source code type used (github, github-ent, gitlab)
    - name: project-id
      description: project id
      default: ""
    - name: ibmcloud-api
      description: the ibmcloud api
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pullrequest-$(params.pr-number)-from-$(params.pr-name)-user
      spec:
        pipelineRef:
          name: pr-pipeline
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: target-branch
            value: $(params.target-branch)
          - name: commit-id
            value: $(params.commit-id)
          - name: commit-timestamp
            value: $(params.commit-timestamp)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: pr-url
            value: $(params.pr-url)
          - name: target-commit-id
            value: $(params.target-commit-id)
          - name: scm-type
            value: $(params.scm-type)
          - name: project-id
            value: $(params.project-id)
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
