apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: trigger-template-kubernetes-service
spec:
  params:
    - name: apikey
      description: the ibmcloud api key
    - name: clusterName
      description: the name of the cluster to target
    - name: resourceGroup
      description: Resource group for the ibmcloud operation
      default: "default"
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: $(params.clusterName)
      spec:
        type: cluster
        params:
          - name: url
            value: https://fake.value
          - name: username
            value: fakevalue
          - name: token
            value: fakevalue
          - name: cadata
            value: fakevalue
    # PVC definition like pre-tekton-0.10.1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-kubernetes-service
        resources:
          - name: target-cluster
            resourceRef:
              name: the-cluster
        params:
          - name: pipeline-pvc
            value: pipelinerun-$(uid)-pvc
          - name: resourceGroup
            value: $(params.resourceGroup)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: trigger-binding-kubernetes-service
spec:
  params:
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener-kubernetes-service
spec:
  triggers:
    - binding:
        name: trigger-binding-kubernetes-service
      template:
        name: trigger-template-kubernetes-service
