---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template-kubernetes-service
spec:
  params:
    - name: cluster-name
      description: the name of the cluster to target
    - name: resource-group
      description: Resource group for the ibmcloud operation
      default: "default"
    - name: pipeline-debug
      default: "0"
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineResource
      metadata:
        name: $(params.cluster-name)
      spec:
        type: cluster
        params:
          # name is required in tekton v0.7 but not in v0.10.1
          - name: name
            value: $(params.cluster-name)
          #
          - name: url
            value: https://fake.value
          - name: username
            value: fakevalue
          - name: token
            value: fakevalue
          - name: cadata
            value: fakevalue
    # PVC definition like pre-tekton-0.10.1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-kubernetes-service
        resources:
          - name: target-cluster
            resourceRef:
              name: $(params.cluster-name)
        params:
          - name: resource-group
            value: $(params.resource-group)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding-kubernetes-service
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener-kubernetes-service
spec:
  triggers:
    - binding:
        name: trigger-binding-kubernetes-service
      template:
        name: trigger-template-kubernetes-service
