apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: kubernetes-service-no-resources
spec:
  params:
    - name: apikey
      description: the ibmcloud api key
    - name: cluster-name
      description: the name of the cluster to target
    - name: resource-group
      description: Resource group for the ibmcloud operation
      default: "default"
  resourcetemplates:
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    # PVC definition like pre-tekton-0.10.1
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: kubernetes-service-no-resources
        params:
          - name: resource-group
            value: $(params.resource-group)
          - name: cluster-name
            value: $(params.cluster-name)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: kubernetes-service-no-resources
spec:
  params:
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: kubernetes-service-no-resources
spec:
  triggers:
    - binding:
        name: kubernetes-service-no-resources
      template:
        name: kubernetes-service-no-resources
