apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: triggertemplate-git-trigger
spec:
  params:
    - name: gitAccessToken
      description: the token to access the git repository for the clone operations
    - name: apikey
      description: the ibmcloud api key
      default: ' '
    - name: repository
      description: The git repo
      default: ' '
    - name: branch
      description: the branch for the git repo
    - name: revision
      description: the commit id/sha for the clone action
      default: ' '
    - name: pr_repository
      description: The source git repo for the PullRequest
      default: ' '
    - name: pr_branch
      description: The source branch for the PullRequest
      default: ' '
    - name: pr_revision
      description: the commit id/sha for the PullRequest
      default: ' '
    - name: triggerName
      default: 'git-pr-process'
  resourcetemplates:
    # CD secret to provide API_KEY to access toolchain information
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: $(params.triggerName)-$(uid)
      spec:
        pipelineRef:
          name: pipeline-git-event-processing
        params:
          - name: pipeline-pvc
            value: $(params.triggerName)-$(uid)-pvc
          - name: gitAccessToken
            value: $(params.gitAccessToken)
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: revision
            value: $(params.revision)
          - name: pr_repository
            value: $(params.pr_repository)
          - name: pr_branch
            value: $(params.pr_branch)
          - name: pr_revision
            value: $(params.pr_revision)
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-manual
spec:
  params:
    - name: repository
      value: $(params.repositoryForManualTrigger)
    - name: branch
      value: "master"
    - name: triggerName
      value: manual-trigger      
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-manual
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-manual
      template:
        name: triggertemplate-git-trigger
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-github-pr
spec:
  params:
    - name: repository
      value: "$(event.pull_request.base.repo.clone_url)"
    - name: branch
      value: "$(event.pull_request.base.ref)"
    - name: pr_repository
      value: "$(event.pull_request.head.repo.clone_url)"
    - name: pr_branch
      value: "$(event.pull_request.head.ref)"
    - name: pr_revision
      value: "$(event.pull_request.head.sha)"
    - name: triggerName
      value: "github-pullrequest"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-github-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.url)"
    - name: revision
      value: "$(event.head_commit.id)"
    - name: branch
      value: "master"
      # value: "$(event.ref)"
    - name: triggerName
      value: "github-commit"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-github-pr
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-github-pr
      template:
        name: triggertemplate-git-trigger
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-github-commit
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-github-commit
      template:
        name: triggertemplate-git-trigger
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-grit-mr
spec:
  params:
    - name: repository
      value: "$(event.object_attributes.target.git_http_url)"
    - name: branch
      value: "$(event.object_attributes.target_branch)"
    - name: pr_repository
      value: "$(event.object_attributes.source.git_http_url)"
    - name: pr_branch
      value: "$(event.object_attributes.source_branch)"
    - name: pr_revision
      value: "$(event.object_attributes.last_commit.id)"
    - name: triggerName
      value: "grit-mergerequest"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-grit-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.git_http_url)"
    - name: revision
      value: "$(event.checkout_sha)"
    - name: branch
      value: "master"
      # value: "$(event.ref)"
    - name: triggerName
      value: "grit-commit"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-grit-mr
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-grit-mr
      template:
        name: triggertemplate-git-trigger
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-grit-commit
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-grit-commit
      template:
        name: triggertemplate-git-trigger
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-bitbucket-pr
spec:
  params:
    - name: repository
      value: "$(event.pullrequest.destination.repository.links.html.href)"
    - name: branch
      value: "$(event.pullrequest.destination.branch.name)"
    - name: pr_repository
      value: "$(event.pullrequest.source.repository.links.html.href)"
    - name: pr_branch
      value: "$(event.pullrequest.source.branch.name)"
    - name: pr_revision
      value: "$(event.pullrequest.source.commit.hash)"
    - name: triggerName
      value: "bitbucket-pullrequest"
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: triggerbinding-git-trigger-bitbucket-commit
spec:
  params:
    - name: repository
      value: "$(event.repository.links.html.href)"
    - name: revision
      value: "$(event.push.changes[0].new.target.hash)"
    - name: branch
      value: "$(event.push.changes[0].new.name)"
    - name: triggerName
      value: "bitbucket-commit"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-bitbucket-pr
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-bitbucket-pr
      template:
        name: triggertemplate-git-trigger
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlistener-git-trigger-bitbucket-commit
spec:
  triggers:
    - binding:
        name: triggerbinding-git-trigger-bitbucket-commit
      template:
        name: triggertemplate-git-trigger
