apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: inspect-content-task
spec:
  inputs:
    params:
      - name: repository
        description: the git repo url
      - name: directoryName
        default: '.'
      - name: propertiesFile
        default: build.properties
      - name: gitCredentialsJsonFile
        default: ''
  workspaces:
  - name: workspace
    mountPath: /artifacts
  steps:
    - name: inspect-git-content
      image: ibmcom/pipeline-base-image
      env:
        - name: REPOSITORY
          value: $(inputs.params.repository)
        - name: DIRECTORY_NAME
          value: $(inputs.params.directoryName)
      workingDir: /artifacts
      command: ["/bin/sh", "-c"]
      args:
        - |
          if [ -z "$DIRECTORY_NAME" ]; then
            # Find the "humanish" part of the git source repository that corresponds to the clone directory
            # REPOSITORY contains the repository url and may end with .git suffix
            DIRECTORY_NAME=$(basename "${REPOSITORY##*/}" .git)
          fi
          cd "$DIRECTORY_NAME"
          # show the git content
          echo "Executing 'git show-branch --all'"
          git show-branch --all
          echo ""
          # show the directory content as a tree
          echo "##############"
          apt-get install tree
          echo "Executing 'tree'"
          tree
          echo ""
          # show the README.md content
          echo "##############"
          echo "Executing 'cat README.md'"
          cat README.md
          echo ""
          echo "##############"
          echo "Executing 'cat $(workspaces.workspace.path)/$(inputs.params.propertiesFile)'"
          cat $(workspaces.workspace.path)/$(inputs.params.propertiesFile)
          echo ""
          if [ "$(inputs.params.gitCredentialsJsonFile)" ]; then
            echo "##############"
            echo "Executing 'jq $(workspaces.workspace.path)/$(inputs.params.gitCredentialsJsonFile)'"
            cat $(workspaces.workspace.path)/$(inputs.params.gitCredentialsJsonFile) | jq '. | ."GIT_TOKEN"="<REDACTED>"'
          fi
