---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: skip-ci
spec:
  params:
    - name: repository
      description: The git repo
    - name: branch
      description: the branch for the git repo
    - name: commit-message
      default: ""
    - name: pipeline-debug
      default: "0"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: skip-ci
        params:
          - name: repository
            value: $(params.repository)
          - name: branch
            value: $(params.branch)
          - name: commit-message
            value: $(params.commit-message)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
        workspaces:
          - name: pipeline-ws
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-commit-binding
spec:
  params:
    - name: repository
      value: "$(event.repository.url)"
    - name: revision
      value: "$(event.head_commit.id)"
    - name: branch
      value: "$(event.ref)"
    - name: commit-message
      value: "$(event.head_commit.message)"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-commit-listener
spec:
  triggers:
    - binding:
        name: github-commit-binding
      template:
        name: skip-ci
