apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-dind
spec:
  inputs:
    params:
      - name: task-pvc
        description: the output pvc - this is the name of the PVC that is mounted for the execution of the task
      - name: imageTag
        description: the image tag
        default: latest
      # Dockerfile location
      - name: pathToDockerfile
        description: the path to the Docker file
        default: /
      - name: dockerfile
        description: The name of the Dockerfile to build from
        default: "Dockerfile"
      - name: continuous-delivery-context-secret
        description: name of the configmap containing the continuous delivery pipeline context secrets
        default: cd-secret
      # Docker Client configuration
      - name: dockerClientImage
        description: The Docker image to use to run the Docker client
        default: docker
      # Docker commands
      - name: propertiesFile
        description: file containing properties out of the docker in docker task
        default: build.properties
      - name: dockerCommands
        description: Shell script that contains the docker commands.
        default: |
            # Default docker build / inspect / push command
            docker build --tag "$IMAGE_URL:$IMAGE_TAG" --file /artifacts$PATH_TO_DOCKERFILE$DOCKERFILE /artifacts$PATH_TO_DOCKERFILE
            docker inspect ${IMAGE_URL}:${IMAGE_TAG}
            docker push ${IMAGE_URL}:${IMAGE_TAG} 2>&1 | tee /steps/docker.log

  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: create-registry-secret
      image: ibmcom/pipeline-base-image
      workingDir: /steps
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: $(inputs.params.continuous-delivery-context-secret)
              key: API_KEY
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail 
          # Get the registry url from builtImage
          REGISTRY_URL=$(echo $(outputs.resources.builtImage.url) |  awk -F/ '{print $1}')
          
          # create a dry-run k8s secret of type docker-registry to obtain
          # the content of a docker config.json file to access the target
          # ibmcloud container registry
          echo "Creating a Kubernetes secret to access the IBM Cloud Container Registry."
          kubectl create secret --dry-run=true --output=json \
            docker-registry registry-dockerconfig-secret \
            --docker-server=${REGISTRY_URL} \
            --docker-password=${API_KEY} \
            --docker-username=iamapikey --docker-email=a@b.com | \
          jq -r '.data[".dockerconfigjson"]' | base64 -d > config.json
          
          echo ""
          echo "Secret created."
      volumeMounts:
        - mountPath: /steps
          name: steps-volume
    - name: run-docker-commands
      image: $(inputs.params.dockerClientImage)
      env:
        - name: IMAGE_TAG
          value: $(inputs.params.imageTag)
        # docker command variables
        - name: PATH_TO_DOCKERFILE
          value: $(inputs.params.pathToDockerfile)
        - name: DOCKERFILE
          value: $(inputs.params.dockerfile)
        # Docker client configuration
        # Connect to the sidecar over TCP, with TLS.
        - name: DOCKER_HOST
          value: tcp://localhost:2376
        # Verify TLS.
        - name: DOCKER_TLS_VERIFY
          value: '1'
        # Use the certs generated by the sidecar daemon.
        - name: DOCKER_CERT_PATH
          value: /certs/client
        # The location of the client configuration files.
        - name: DOCKER_CONFIG
          value: /steps
      command: ["/bin/sh", "-c"]
      args:
        - |
          set -e -o pipefail
          IMAGE_URL=$(echo $(outputs.resources.builtImage.url) |  awk -F: '{print $1}')
          echo "Image URL: $IMAGE_URL"
          echo "Image tag: $IMAGE_TAG"
          echo ""

          # run docker commad(s) passed as parameter
          echo "Running docker command(s)..."
          echo ""

          $(inputs.params.dockerCommands)

          echo ""
          echo "Done."
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
        - mountPath: /steps
          name: steps-volume
        - mountPath: /certs/client
          name: dind-certs
    - name: process-docker-log
      image: alpine
      workingDir: /steps
      env:
        - name: PROPERTIES_FILE
          value: $(inputs.params.propertiesFile)
      command: ["/bin/sh", "-c"]
      args:
        - |
          set -e -o pipefail
          
          # Parse the image url to find information (region, namespace, image name)
          IMAGE_URL=$(echo $(outputs.resources.builtImage.url) |  awk -F: '{print $1}')
          IMAGE_TAG=$(inputs.params.imageTag)
          REGISTRY_URL=$(echo $(outputs.resources.builtImage.url) |  awk -F/ '{print $1}')
          REGISTRY_NAMESPACE=$(echo $(outputs.resources.builtImage.url) |  awk -F/ '{print $2}')
          IMAGE_NAME=$(echo $(outputs.resources.builtImage.url) |  awk -F/ '{print $3}')
          # get sha from the docker log
          MANIFEST_SHA=$(grep -i 'sha256:' /steps/docker.log | awk '{print $3}')
          
          if [ "$PROPERTIES_FILE" ]; then
            cd /artifacts
            touch $PROPERTIES_FILE
            echo "REGISTRY_URL=${REGISTRY_URL}" >> $PROPERTIES_FILE
            echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}" >> $PROPERTIES_FILE
            echo "REGISTRY_REGION=${REGISTRY_REGION}" >> $PROPERTIES_FILE
            echo "IMAGE_NAME=${IMAGE_NAME}" >> $PROPERTIES_FILE
            echo "IMAGE_TAGS=${IMAGE_TAG}" >> $PROPERTIES_FILE
            echo "IMAGE_MANIFEST_SHA=${MANIFEST_SHA}" >> $PROPERTIES_FILE
            echo "$PROPERTIES_FILE content:"
            cat $PROPERTIES_FILE
          fi
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
        - mountPath: /steps
          name: steps-volume
  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
    - name: steps-volume
      emptyDir: {}
    - name: dind-certs
      emptyDir: {}
  sidecars:
    - image: docker:dind
      name: server
      securityContext:
        privileged: true
      env:
        # Write generated certs to the path shared with the client.
        - name: DOCKER_TLS_CERTDIR
          value: /certs
      volumeMounts:
        - mountPath: /certs/client
          name: dind-certs
      # Wait for the dind daemon to generate the certs it will share with the client.
      readinessProbe:
        periodSeconds: 1
        exec:
          command: ["ls", "/certs/client/ca.pem"]
