apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: containerize-task
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc - this is the volume where the files (Dockerfile etc..) are expected to be
      - name: ibmcloudApi
        description: the ibmcloud api
        default: https://cloud.ibm.com
      - name: continuous-delivery-context-secret
        description: name of the configmap containing the continuous delivery pipeline context secrets
        default: cd-secret
      - name: container-registry-apikey-secret-key
        description: field in the secret that contains the api key used to login to ibmcloud container registry
        default: 'API_KEY'
      - name: resourceGroup
        description: target resource group (name or id) for the ibmcloud login operation
        default: ''
      - name: image-url
        description: "url of the image to build - required if no image pipeline resource provided to this task"
        default: ""
      - name: pathToContext
        default: .
      - name: pathToDockerfile
        default: .
      - name: dockerfile
        description: The name of the Dockerfile
        default: "Dockerfile"
      - name: buildArgs
        description: build argument list in the format 'KEY=VALUE' with a key-value pair per line.
        default: ""
      - name: buildkit_image
        description: The name of the BuildKit image
        default: "moby/buildkit:v0.6.3-rootless"
      - name: additionalTags
        description: comma-separated list of additionalTags
        # can not be defined as an array because of variable substition error for array
        # https://github.com/tektoncd/pipeline/commit/86deacb04536f0f3e7176c6664cec8786678ed18
        default: ''
      - name: additionalTagsScript
        description: Shell script that allows to add tags for the image to be build.
        default: ''
      - name: propertiesFile
        description: file containing properties out of containerize task
        default: build.properties
      - name: pipeline-debug
        description: Pipeline debug mode
        default: "0"
  outputs:
    resources:
      - name: builtImage
        type: image
        description: "(Optional) The image to build"
        optional: true
  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(inputs.params.pipeline-debug)
  steps:
    - name: check-registry
      image: ibmcom/pipeline-base-image:2.6
      workingDir: /steps
      env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: $(inputs.params.continuous-delivery-context-secret)
              key: $(inputs.params.container-registry-apikey-secret-key)
        - name: IBMCLOUD_API
          value: $(inputs.params.ibmcloudApi)
        - name: IBMCLOUD_RESOURCE_GROUP
          value: $(inputs.params.resourceGroup)
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail

          if [ $PIPELINE_DEBUG == 1 ]; then
              pwd
              env
              trap env EXIT
              set -x
          fi

          ##########################################################################
          # Setting HOME explicitly to have ibmcloud plugins available
          # doing the export rather than env definition is a workaround
          # until https://github.com/tektoncd/pipeline/issues/1836 is fixed
          export HOME="/root"
          ##########################################################################

          if [ "$(outputs.resources.builtImage.url)" == "" ]; then
            export IMAGE_RESOURCE_URL="$(inputs.params.image-url)"
          else
            export IMAGE_RESOURCE_URL="$(outputs.resources.builtImage.url)"
          fi

          # Ensure login to the container registry and namespace available
          source /scripts/check_registry.sh

          # create a dry-run k8s secret of type docker-registry to obtain
          # the content of a docker config.json file to access the target
          # ibmcloud container registry
          kubectl create secret --dry-run=true --output=json \
            docker-registry registry-dockerconfig-secret \
            --docker-server=${REGISTRY_URL} \
            --docker-password=${API_KEY} \
            --docker-username=iamapikey --docker-email=a@b.com | \
          jq -r '.data[".dockerconfigjson"]' | base64 -d > config.json

          echo "REGISTRY_URL=${REGISTRY_URL}" > next-step-env.properties
          echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}" >> next-step-env.properties
          echo "REGISTRY_REGION=${REGISTRY_REGION}" >> next-step-env.properties
          echo "IMAGE_URL=${IMAGE_URL}" >> next-step-env.properties
          echo "IMAGE_TAG=${IMAGE_TAG}" >> next-step-env.properties
          echo "IMAGE_NAME=${IMAGE_NAME}" >> next-step-env.properties
      volumeMounts:
        - mountPath: /cd-config
          name: cd-config-volume
        - mountPath: /steps
          name: steps-volume
        - mountPath: /scripts
          name: check-registry-script
    - name: build-image
      image: $(inputs.params.buildkit_image)
      workingDir: /artifacts
      env:
        # specifying DOCKER_CONFIG is required to allow buildkit to detect docker credentials
        - name: DOCKER_CONFIG
          value: /steps
        # CD execution context injection
        - name: PIPELINE_RUN_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tekton.dev/pipelineRun']
        - name: PIPELINE_RUN_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/tekton-pipeline']
        - name: BUILD_NUMBER
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/build-number']
        - name: PIPELINE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/pipeline-id']
        - name: TRIGGER_TYPE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/trigger-type']
        - name: TRIGGER_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/trigger-name']
        - name: TRIGGERED_BY
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['devops.cloud.ibm.com/triggered-by']
      securityContext:
        privileged: true
      command: ["/bin/sh", "-c"]
      args:
        - |
          if [ $PIPELINE_DEBUG == 1 ]; then
              pwd
              env
              trap env EXIT
              set -x
          fi

          source /steps/next-step-env.properties
          export $(cut -d= -f1 /steps/next-step-env.properties)

          # Manage multiple tags for an image
          # Add dynamically computed tags
          printf "#!/bin/sh\n" > /steps/additionnalTags.sh
          printf "%s " '$(inputs.params.additionalTagsScript)' >> /steps/additionnalTags.sh
          chmod +x /steps/additionnalTags.sh
          /steps/additionnalTags.sh 2 >& 1 > /steps/tags.lst
          # Add image pipeline resource
          if [ "${IMAGE_TAG}" ]; then
            echo "${IMAGE_TAG}" >> /steps/tags.lst
          fi
          # Add tags provided using task parameter
          if [ "$(inputs.params.additionalTags)" ];  then
            echo "$(inputs.params.additionalTags)" | sed 's/,/\n/g' >> /steps/tags.lst
          fi
          echo "#######################"
          echo "Image Tags:"
          cat /steps/tags.lst
          echo "#######################"
          # Add the full image url with tags - use # as separator in case IMAGE_NAME contains /
          sed -i "s#^#$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME:#" /steps/tags.lst
          sort -u -o /steps/tags.lst /steps/tags.lst
          echo "Full Image URLs:"
          cat /steps/tags.lst
          echo "#######################"
          BUILDKIT_IMAGE_NAMES=$(tr -s '\r\n' ',' < /steps/tags.lst | sed -e 's/,$/\n/')
          if [ -z "$BUILDKIT_IMAGE_NAMES" ]; then
            # Set default image name for buildkit to push
            BUILDKIT_IMAGE_NAMES="$REGISTRY_URL/$REGISTRY_NAMESPACE/$IMAGE_NAME"
          fi
          echo "Buildkit Image names: $BUILDKIT_IMAGE_NAMES"

          BUILD_ARG_LIST='$(inputs.params.buildArgs)'
          for buildArg in $BUILD_ARG_LIST; do
            BUILD_ARGS="${BUILD_ARGS} --opt build-arg:$buildArg "
          done

          if [ "$(outputs.resources.builtImage.url)" == "" ]; then
            export IMAGE_RESOURCE_URL="$(inputs.params.image-url)"
          else
            export IMAGE_RESOURCE_URL="$(outputs.resources.builtImage.url)"
          fi

          buildctl-daemonless.sh build \
            --progress=plain \
            --frontend=dockerfile.v0 \
            --opt filename=$(inputs.params.dockerfile) \
            ${BUILD_ARGS} \
            --local context=/artifacts/$(inputs.params.pathToContext) --local dockerfile=/artifacts/$(inputs.params.pathToDockerfile) \
            --exporter=image --exporter-opt "name=$BUILDKIT_IMAGE_NAMES" --exporter-opt "push=true" \
            --export-cache type=inline \
            --import-cache type=registry,ref=$IMAGE_RESOURCE_URL 2>&1 | tee /steps/build.log

          # Using the deprecated --exporter option for now as the multiple name/tags using --output option
          # is not working as expected: https://github.com/moby/buildkit/issues/797#issuecomment-581346240
          #  --output type=image,"name=$(outputs.resources.builtImage.url):1.0.0,$(outputs.resources.builtImage.url)",push=true \

          # it is not possible to specify multiple exporters for now
          # --output type=oci,dest=/builder/home/image-outputs/builtImage/output.tar \
          # It is possible to assign multiple tags to the image with latest version of buildkit_image
          # see https://github.com/moby/buildkit/issues/797

      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
        - mountPath: /steps
          name: steps-volume
    - name: process-build-log
      # An image including only jq should be sufficient
      image: ibmcom/pipeline-base-image:2.6
      workingDir: /steps
      env:
        - name: PROPERTIES_FILE
          value: $(inputs.params.propertiesFile)
      command: ["/bin/bash", "-c"]
      args:
        - |
          set -e -o pipefail

          if [ $PIPELINE_DEBUG == 1 ]; then
              pwd
              env
              trap env EXIT
              set -x
          fi

          source /steps/next-step-env.properties
          export $(cut -d= -f1 /steps/next-step-env.properties)

          # buildctl/buildkit does not provide an index.json as part of the output
          # https://github.com/moby/buildkit/issues/1158 and https://github.com/moby/buildkit/issues/993
          # https://github.com/moby/buildkit/pull/1315
          # unfortunately, this is needed for Tekton Image Pipeline Resource
          # https://github.com/tektoncd/pipeline/blob/v0.7.0/docs/resources.md#image-resource
          # so workaround for now is to process the buildkit log to find the required information

          MANIFEST_SHA=$(grep -i 'exporting manifest' build.log | grep -i 'done' | awk '{print $4}')
          CONFIG_SHA=$(grep -i 'exporting config' build.log | grep -i 'done' | awk '{print $4}')
          FULLY_QUALIFIED_IMAGE=$(grep -i 'pushing manifest' build.log | grep -i 'done' | awk '{print $5}')

          if [ "$(outputs.resources.builtImage.url)" ]; then
            echo "Creating OCI image index - index.json - out of the build.log to reference image sha: $MANIFEST_SHA"
            # ibmcloud container-registry image manifest is: application/vnd.docker.distribution.manifest.v2+json
            echo "{}" | \
            jq --arg manifest_sha "$MANIFEST_SHA" '{schemaVersion:2,manifests:[{"mediaType": "application/vnd.oci.image.manifest.v1+json", digest:$manifest_sha}]}' 2>&1 | \
            tee /workspace/output/builtImage/index.json

            # Copy the index.json to the legacy location - v0.7.0 - for such imageoutput
            mkdir -p /builder/home/image-outputs/builtImage
            cp /workspace/output/builtImage/index.json /builder/home/image-outputs/builtImage
          fi

          # Because of https://github.com/tektoncd/pipeline/issues/216
          # the image digest for input is/will always empty
          # there was an alternative/workaround but it is updating using a specific account
          # and using a kubectl command to update the resources
          # see https://github.com/nlewo/poc-tekton#deploy-tasks
          # https://raw.githubusercontent.com/tektoncd/catalog/0b48da8e336a4214aff46af242658dc056199b1c/update-image-digests/image-digest-updater.yaml
          # https://raw.githubusercontent.com/tektoncd/catalog/0b48da8e336a4214aff46af242658dc056199b1c/update-image-digests/update-image-digests.yaml
          # Here the workaround will be to add registry and image information in an output properties file
          if [ "$PROPERTIES_FILE" ]; then
            cd /artifacts
            touch $PROPERTIES_FILE
            echo "REGISTRY_URL=${REGISTRY_URL}" >> $PROPERTIES_FILE
            echo "REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}" >> $PROPERTIES_FILE
            echo "REGISTRY_REGION=${REGISTRY_REGION}" >> $PROPERTIES_FILE
            echo "IMAGE_NAME=${IMAGE_NAME}" >> $PROPERTIES_FILE
            echo "IMAGE_TAGS=$(grep -i 'pushing manifest' /steps/build.log | grep -i 'done' | awk '{print $5}' | awk -F: '{print $2}' | tr -s '\r\n' ',' | sed -e 's/,$/\n/')" >> $PROPERTIES_FILE
            echo "IMAGE_MANIFEST_SHA=${MANIFEST_SHA}" >> $PROPERTIES_FILE
            echo "$PROPERTIES_FILE content:"
            cat $PROPERTIES_FILE
          fi
      volumeMounts:
        - mountPath: /artifacts
          name: task-volume
        - mountPath: /steps
          name: steps-volume
  volumes:
    - name: steps-volume
      emptyDir: {}
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
    - name: cd-config-volume
      configMap:
        name: toolchain
        items:
        - key: toolchain.json
          path: toolchain.json
    - name: check-registry-script
      configmap: 
        name: check-registry-script
        items: 
        - key: check_registry.sh
          path: check_registry.sh          