---
apiVersion: tekton.dev/v1
kind: EventListener
metadata:
  name: github-listener
  annotations:
    tekton.dev/displayName: "github enterprise pull-request listener"
spec:
  triggers:
    - bindings:
        - name: github-binding
      template:
        name: template-cra
---
apiVersion: tekton.dev/v1
kind: EventListener
metadata:
  name: gl-ci-listener
  annotations:
    tekton.dev/displayName: "github enterprise commit push listener"
spec:
  triggers:
    - bindings:
        - name: gl-ci-binding
      template:
        name: template-cra
---
apiVersion: tekton.dev/v1
kind: EventListener
metadata:
  name: gl-pr-listener
  annotations:
    tekton.dev/displayName: "grit/gitlab pull-request listener"
spec:
  triggers:
    - bindings:
        - name: gl-pr-binding
      template:
        name: template-cra
