---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template-cra
spec:
  params:
    - name: apikey
      description: The ibmcloud api key
    - name: ibmcloud-api
      description: The ibmcloud api
      default: "https://cloud.ibm.com"
    - name: ibmcloud-region
      description: (Optional) ibmcloud region to use
      default: ""
    - name: pipeline-debug
      description: Toggles debug mode for the pipeline
      default: "0"
    - name: registry-region
      description: (Optional) The ibmcloud container registry region
      default: ""
    - name: resource-group
      description: (Optional) Target resource group (name or id) for the ibmcloud login operation
      default: ""

    # Event params
    - name: branch
      description: The git branch
      default: ""
    - name: commit-id
      description: commit id
      default: ""
    - name: pr-branch
      description: The branch in the forked git repo from where the PR is made
      default: ""
    - name: pr-repository
      description: The forked git repo from where the PR is made
      default: ""
    - name: repository
      description: The git repo
    - name: git-credentials-json-file
      description: (Optional) JSON file containing the git credentials as found out of the clone task
      default: "output/secrets/thecredentials.json"

    # Common command related params
    - name: custom-script
      description: (Optional) Filepath to a custom script that is ran prior to CRA scanning
      default: ""
    - name: env-props
      description: (Optional) A custom configuration of environment properties to source before execution, ex. 'export ABC=123 export DEF=456'
      default: ""
    - name: fileignore
      description: (Optional) Filepath to .fileignore
      default: ""
    - name: ibmcloud-trace
      description: (Optional) Enables IBMCLOUD_TRACE for ibmcloud cli logging
      default: "false"
    - name: output
      description: (Optional) Prints command result to console
      default: "false"
    - name: path
      description: Repository path to scan
      default: "/artifacts"
    - name: strict
      description: (Optional) Enables strict mode for scanning
      default: "false"
    - name: toolchainid
      description: (Optional) The target toolchain id to be used. Defaults to the current toolchain id
      default: ""
    - name: verbose
      description: (Optional) Enable verbose log messages
      default: "false"

    # BOM related params
    - name: asset-type
      description: Security checks to run (apps, image, os, all)
      default: "all"
    - name: bom-report
      description: Filepath to store generated Bill of Materials
      default: "bom.json"
    - name: docker-build-flags
      description: (Optional) Customize docker build command for build stage scanning
      default: ""
    - name: docker-build-context
      description: (Optional) If specified, CRA will use the directory in the path parameter as docker build context
    - name: dockerfile-pattern
      description: (Optional) Pattern to identify Dockerfile in the repository
    - name: docker-registry-secret
      description: Secret to authenticate for docker-registry-url
    - name: docker-registry-url
      description: Registry url to use for docker login
      default: ""
    - name: docker-registry-username
      description: Username to authenticate for docker-registry-url
      default: ""
    - name: gradle-exclude-configs
      description: (Optional) Exclude gradle configurations, ex. 'runtimeClasspath,testCompileClasspath'
      default: ""
    - name: gradle-props
      description: (Optional) Customize gradle command with props for gradle dependency scanning.
      default: ""
    - name: maven-exclude-scopes
      description: (Optional) Exclude maven scopes, ex. 'test,compile'
      default: ""
    - name: nodejs-create-package-lock
      description: (Optional) Enable the task to build the package-lock.json for node.js projects
      default: "false"
    - name: prev-report
      description: Filepath to previous BoM report to skip Dockerfile or application manifest scans
      default: ""

    # Deploy Analytic related params
    - name: deploy-report
      description: Filepath to store generated Deploy Analytic report
      default: "deploy.json"

    # Vulnerability related params
    - name: cveignore
      description: (Optional) Filepath to cveignore
      default: ""
    - name: exclude-dev
      description: (Optional) Exclude dev dependencies during vulnerability scan
      default: "false"
    - name: vulnerability-report
      description: Filepath to store Vulnerability report, not stored if empty
      default: "vulnerability.json"

    # Terraform related parameters
    - name: terraform-report
      description: Filepath to store generated Terraform report
      default: "terraform.json"
    - name: tf-dir
      description: (Optional) The directory where the terraform main entry file is found if not in parent directory
      default: ""
    - name: tf-plan
      description: (Optional) Filepath to Terraform Plan file.
      default: ""
    - name: tf-var-file
      description: (Optional) terraform var-file
      default: ""
    - name: tf-version
      description: (Optional) The terraform version to use to create Terraform plan
      default: "0.15.5"
    - name: tf-policy-file
      description: (Optional) Filepath to policy profile. This flag can accept an SCC V2 profile or a custom json file with a set of SCC rules.
      default: ""
    - name: tf-attachment-file
      description: (Optional) Path of SCC V2 attachment file.
      default: ""

    # User control params
    - name: cra-scan-image
      description: Image to use for `scan` task
      default: "icr.io/continuous-delivery/pipeline/pipeline-base-ubi:3.11"
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage: 5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        API_KEY: $(params.apikey)
        DOCKER_SECRET: $(params.docker-registry-secret)
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline-cra
        workspaces:
          - name: artifacts
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: ibmcloud-api
            value: $(params.ibmcloud-api)
          - name: ibmcloud-region
            value: $(params.ibmcloud-region)
          - name: pipeline-debug
            value: $(params.pipeline-debug)
          - name: registry-region
            value: $(params.registry-region)
          - name: resource-group
            value: $(params.resource-group)
          - name: branch
            value: $(params.branch)
          - name: commit-id
            value: $(params.commit-id)
          - name: pr-branch
            value: $(params.pr-branch)
          - name: pr-repository
            value: $(params.pr-repository)
          - name: repository
            value: $(params.repository)
          - name: git-credentials-json-file
            value: $(params.git-credentials-json-file)
          - name: custom-script
            value: $(params.custom-script)
          - name: env-props
            value: $(params.env-props)
          - name: fileignore
            value: $(params.fileignore)
          - name: ibmcloud-trace
            value: $(params.ibmcloud-trace)
          - name: output
            value: $(params.output)
          - name: path
            value: $(params.path)
          - name: strict
            value: $(params.strict)
          - name: toolchainid
            value: $(params.toolchainid)
          - name: verbose
            value: $(params.verbose)
          - name: asset-type
            value: $(params.asset-type)
          - name: bom-report
            value: $(params.bom-report)
          - name: docker-build-flags
            value: $(params.docker-build-flags)
          - name: docker-build-context
            value: $(params.docker-build-context)
          - name: dockerfile-pattern
            value: $(params.dockerfile-pattern)
          - name: docker-registry-url
            value: $(params.docker-registry-url)
          - name: docker-registry-username
            value: $(params.docker-registry-username)
          - name: gradle-exclude-configs
            value: $(params.gradle-exclude-configs)
          - name: gradle-props
            value: $(params.gradle-props)
          - name: maven-exclude-scopes
            value: $(params.maven-exclude-scopes)
          - name: nodejs-create-package-lock
            value: $(params.nodejs-create-package-lock)
          - name: prev-report
            value: $(params.prev-report)
          - name: deploy-report
            value: $(params.deploy-report)
          - name: cveignore
            value: $(params.cveignore)
          - name: exclude-dev
            value: $(params.exclude-dev)
          - name: vulnerability-report
            value: $(params.vulnerability-report)
          - name: terraform-report
            value: $(params.terraform-report)
          - name: tf-dir
            value: $(params.tf-dir)
          - name: tf-plan
            value: $(params.tf-plan)
          - name: tf-var-file
            value: $(params.tf-var-file)
          - name: tf-version
            value: $(params.tf-version)
          - name: tf-policy-file
            value: $(params.tf-policy-file)
          - name: tf-attachment-file
            value: $(params.tf-attachment-file)
          - name: cra-scan-image
            value: $(params.cra-scan-image)
