---        
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cra-comm-editor
spec:  
  params:
    - name: repository
      description: the git repo url
    - name: pr-url
      description: merge request url
      default: ""
    - name: project-id
      description: project id
      default: ""
    - name: comment-fp
      description: comments filepath
    - name: scm-type
      description: source code type used (github, github-ent, gitlab)   
  
  steps:
    - name: comm-editor
      image: icr.io/continuous-delivery/cra-comm-editor:main.995
      imagePullPolicy: Always
      workingDir: "/artifacts"
      command: ["/bin/sh", "-c"]
      args:
        - |
          #!/bin/sh
          ls -la .
          
          GIT_PROPS_FILE=./build.properties
          if [ ! -f "$GIT_PROPS_FILE" ]; then
            echo "Build properties file not found: $GIT_PROPS_FILE"
            exit 1
          fi
          
          GIT_USER=$(grep GIT_AUTH_USER  $GIT_PROPS_FILE | cut -d "=" -f2)
          if [ $(params.scm-type) = "github-ent" ]; then
              GIT_TOKEN=$(grep GHE_TOKEN  $GIT_PROPS_FILE | cut -d "=" -f2)
              echo "setting git token"
          else
              GIT_TOKEN=$(grep GIT_TOKEN  $GIT_PROPS_FILE | cut -d "=" -f2)
              echo "setting git-ent token"
          fi    

          export GIT_USER
          export GIT_TOKEN
           
          /usr/local/bin/comm-editor \
            -repo-url "$(params.repository)" \
            -pr-url "$(params.pr-url)" \
            -token "$GIT_TOKEN" \
            -user "$GIT_USER" \
            -comment-fp "$(params.comment-fp)" \
            -project-id "$(params.project-id)" \
            -scm-type "$(params.scm-type)"

  workspaces:
    - name: artifacts
      mountPath: /artifacts