---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: toolchain-build-scan
spec:
  params:
    - name: repository
      description: the git repo
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
  workspaces:
    - name: output
      description: The git repo will be cloned onto the volume backing this workspace
      mountPath: /artifacts
  steps:
    - name: scan-repo
      image: ibmcom/pipeline-base-image:2.6
      env:
        - name: PIPELINE_DEBUG
          value: $(params.pipeline-debug)
        - name: GIT_REPO
          value: $(params.repository)
      workingDir: "/artifacts"
      script: |
        #!/bin/bash
        set -e -o pipefail;

        if [ $PIPELINE_DEBUG == 1 ]; then
          pwd
          env
          trap env EXIT
          set -x
        fi

        #Scan the repo for a 'pom.xml' file
        echo "The Git repo is: $GIT_REPO"
        if [[ -n $(find /artifacts -name pom.xml) ]]; then
          echo "Found 'pom.xml' file"
          echo "BUILD_REQUIRED='true'" >> /steps/next-step-env.properties
        else
          echo "No 'pom.xml' file found"
          echo "BUILD_REQUIRED='false'" >> /steps/next-step-env.properties
        fi
      volumeMounts:
        - mountPath: /steps
          name: steps-volume
    - name: build-check
      image: ibmcom/pipeline-base-image:2.6
      env:
        - name: PIPELINE_DEBUG
          value: $(params.pipeline-debug)
      workingDir: "/artifacts"
      script: |
        #!/bin/bash
        set -e -o pipefail;

        if [ $PIPELINE_DEBUG == 1 ]; then
          pwd
          env
          trap env EXIT
          set -x
        fi

        #Check to see if addtional build is required and run it if needed
        source /steps/next-step-env.properties
        if [ "$BUILD_REQUIRED" == "true" ]; then
          echo "Additional build required. Running Maven build."
          mvn -B package
        else
          echo "No additional build required"
        fi

      volumeMounts:
        - mountPath: /steps
          name: steps-volume
  volumes:
    - name: steps-volume
      emptyDir: {}