---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: toolchain-build-scan
spec:
  params:
    - name: repository
      description: the git repo
    - name: pipeline-debug
      description: Pipeline debug mode
      default: "0"
  results:
    - name: build_needed
      description: Determines if additional build is required
  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)
      - name: GIT_REPO
        value: $(params.repository)
  steps:
    - name: scan-repo
      image: ibmcom/pipeline-base-image:2.6
      command: [ "/bin/bash", "-c" ]
      args:
        - |
          #!/bin/bash
          set -e -o pipefail;

          if [ $PIPELINE_DEBUG == 1 ]; then
            pwd
            env
            trap env EXIT
            set -x
          fi

          #Scan the repo for a 'pom.xml' file
          if [[ -n $(find $GIT_REPO -name pom.xml) ]]; then
            #There is a 'pom.xml' file
            echo "true" > $(results.build_needed.path)
          else
            #Could not find a 'pom.xml' file in the repo
            echo "false" > $(results.build_needed.path)
          fi
    - name: build-check
      image: ibmcom/pipeline-base-image:2.6
      command: [ "/bin/bash", "-c" ]
      args:
        - |
          #!/bin/bash
          set -e -o pipefail;

          if [ $PIPELINE_DEBUG == 1 ]; then
            pwd
            env
            trap env EXIT
            set -x
          fi

          #Scan the repo for a 'pom.xml' file
          if [ "$(results.build_needed.path)" == "true" ]; then
            echo "Found 'pom.xml' file"
            mvn -B package
          else
            echo "No 'pom.xml' file found"
          fi
